# Generated by Django 3.2.5 on 2021-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='send_to_staff',
            field=models.ManyToManyField(to='My_App.Staff'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='send_to_student',
            field=models.ManyToManyField(to='My_App.Student'),
        ),
        migrations.AlterField(
            model_name='staffnotification',
            name='send_to_student',
            field=models.ManyToManyField(to='My_App.Student'),
        ),
    ]
