# Generated by Django 3.2.5 on 2021-10-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0002_auto_20211016_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
