# Generated by Django 3.2.5 on 2021-10-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0003_alter_staffnotification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
